@extends('layouts.student')

@section('title', 'Classroom Integration — TrackTern')
@section('page_heading', 'Classroom Integration')
@section('nav_classroom', 'active')

@section('content')
<div class="table-container" style="padding: 24px; margin-bottom: 30px;">
  <h3>Join Teacher's Classroom</h3>
  <p id="join-classroom-note" style="font-size: 14px; color: #4B5563; margin-bottom: 16px;">Enter the 5-digit Classroom Invitation Code generated by your instructor.</p>
  <form id="join-classroom-form" onsubmit="handleJoinClassroom(event)" style="display: flex; gap: 16px; max-width: 450px; flex-wrap: wrap;">
    <input type="text" id="join-code" placeholder="Enter 5-digit Code (e.g. CR902)" maxlength="5" style="text-transform: uppercase; font-weight:700; flex: 1; min-width: 220px;" required>
    <button type="submit" id="join-classroom-button" class="btn-primary" style="white-space: nowrap;">Join Class</button>
  </form>
</div>

<div class="table-container">
  <div class="table-header">
    <h3>Enrolled Classrooms</h3>
  </div>
  <table class="solid-table">
    <thead>
      <tr>
        <th>Classroom Name</th>
        <th>Code</th>
        <th>Teacher</th>
        <th>Required Hours</th>
        <th>Status</th>
        <th>Information</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody id="classroom-list-tbody">
      <tr><td colspan="7" style="text-align:center;">Loading classroom enrollments...</td></tr>
    </tbody>
  </table>
</div>

<div id="classroom-info-modal" class="app-modal-backdrop" hidden aria-hidden="true">
  <div class="app-modal-card" role="dialog" aria-modal="true" aria-labelledby="classroom-info-title" style="width:min(1040px, 100%);">
    <div class="app-modal-header">
      <div>
        <div style="font-size: 12px; color: #6B7280; text-transform: uppercase; font-weight: 800;">Classroom Information</div>
        <h3 id="classroom-info-title" style="margin-top: 4px;">Classroom</h3>
      </div>
      <button type="button" class="icon-action-button" aria-label="Close classroom information" onclick="closeClassroomInfo()">
        <svg viewBox="0 0 24 24"><path d="M18 6 6 18M6 6l12 12"/></svg>
      </button>
    </div>
    <div class="detail-tabs" role="tablist" aria-label="Classroom detail tabs">
      <button type="button" id="classroom-tab-info" class="detail-tab-button active" onclick="switchClassroomInfoTab('info')">Classroom</button>
      <button type="button" id="classroom-tab-tasks" class="detail-tab-button" onclick="switchClassroomInfoTab('tasks')">Tasks</button>
      <button type="button" id="classroom-tab-dtr" class="detail-tab-button" onclick="switchClassroomInfoTab('dtr')">DTR</button>
    </div>
    <div id="classroom-info-content"></div>
  </div>
</div>
@endsection

@section('scripts')
<script>
  let enrolledClassrooms = [];
  let selectedClassroomId = null;
  let selectedClassroomTasks = [];
  let selectedClassroomAttendance = [];
  let selectedClassroomDtrMonth = new Date();

  function escapeHtml(value) {
    return String(value ?? '').replace(/[&<>"']/g, char => ({
      '&': '&amp;',
      '<': '&lt;',
      '>': '&gt;',
      '"': '&quot;',
      "'": '&#039;',
    }[char]));
  }

  function formatDate(value) {
    return formatAppDate(value);
  }

  function formatTime(value) {
    return formatAppTime(value);
  }

  function renderStatusBadge(status) {
    const normalized = String(status || '').toLowerCase();
    const badgeClass = ['approved', 'completed', 'active'].includes(normalized)
      ? 'badge-approved'
      : (['pending', 'open'].includes(normalized) ? 'badge-pending' : 'badge-rejected');

    return `<span class="badge ${badgeClass}">${escapeHtml(String(status || 'pending').replace('_', ' '))}</span>`;
  }

  function renderAttachments(attachments) {
    if (!attachments || attachments.length === 0) return '<em>No attachments</em>';

    return `
      <div class="attachment-list">
        ${attachments.map(attachment => {
          return renderAttachmentPreviewButton(attachment);
        }).join('')}
      </div>
    `;
  }

  function getSelectedClassroom() {
    return enrolledClassrooms.find(c => Number(c.id) === Number(selectedClassroomId));
  }

  function getLocalDateKey(date) {
    return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
  }

  function getDateValue(value) {
    return value ? String(value).slice(0, 10) : '';
  }

  function getTaskForAttendance(attendanceId) {
    return selectedClassroomTasks.find(task => Number(task.attendance_id) === Number(attendanceId));
  }

  function renderClassroomInfoPanel(classroom) {
    const teacherName = classroom.teacher && classroom.teacher.user ? classroom.teacher.user.name : 'N/A';
    const teacherContact = classroom.teacher && classroom.teacher.contact_number ? classroom.teacher.contact_number : 'N/A';

    return `
      <div class="info-grid">
        <div class="info-row"><strong>Classroom Code</strong><span>${escapeHtml(classroom.classroom_code)}</span></div>
        <div class="info-row"><strong>Teacher</strong><span>${escapeHtml(teacherName)}</span></div>
        <div class="info-row"><strong>Teacher Phone</strong><span>${escapeHtml(teacherContact)}</span></div>
        <div class="info-row"><strong>Required Hours</strong><span>${escapeHtml(classroom.required_hours)} hrs</span></div>
        <div class="info-row"><strong>Semester</strong><span>${escapeHtml(classroom.semester || 'N/A')}</span></div>
        <div class="info-row"><strong>Academic Year</strong><span>${escapeHtml(classroom.academic_year || 'N/A')}</span></div>
        <div class="info-row"><strong>Joined</strong><span>${formatDate(classroom.pivot ? classroom.pivot.joined_at : null)}</span></div>
        <div class="info-row"><strong>Created</strong><span>${formatDate(classroom.created_at)}</span></div>
      </div>
    `;
  }

  function renderClassroomTasksPanel() {
    return `
      <div style="overflow-x:auto;">
        <table class="solid-table">
          <thead>
            <tr>
              <th>DTR Date</th>
              <th>Time In</th>
              <th>Time Out</th>
              <th>Rendered Hours</th>
              <th>Title & Details</th>
              <th>Status</th>
              <th>Teacher Feedback</th>
              <th>Attachments</th>
            </tr>
          </thead>
          <tbody>
            ${selectedClassroomTasks.length > 0 ? selectedClassroomTasks.map(task => {
              const attendance = task.attendance || {};
              return `
                <tr>
                  <td>${attendance.date ? formatDate(attendance.date) : 'N/A'}</td>
                  <td>${attendance.time_in ? formatTime(attendance.time_in) : 'N/A'}</td>
                  <td>${attendance.time_out ? formatTime(attendance.time_out) : 'N/A'}</td>
                  <td>${Number(attendance.rendered_hours || 0).toFixed(2)} hrs</td>
                  <td><strong>${escapeHtml(task.title)}</strong><br><small style="color:#6B7280;">${escapeHtml(task.description)}</small></td>
                  <td>${renderStatusBadge(task.status)}</td>
                  <td>${task.teacher_feedback ? escapeHtml(task.teacher_feedback) : '<em>No feedback yet</em>'}</td>
                  <td>${renderAttachments(task.attachments)}</td>
                </tr>
              `;
            }).join('') : '<tr><td colspan="8" style="text-align:center;">No accomplishment reports submitted for this classroom.</td></tr>'}
          </tbody>
        </table>
      </div>
    `;
  }

  function renderClassroomDtrDetails(record) {
    if (!record) {
      return '<p style="margin-top:0;color:#4B5563;">Select a DTR date to view the exact attendance details and submitted task.</p>';
    }

    const task = getTaskForAttendance(record.id);
    return `
      <div class="info-grid">
        <div class="info-row"><strong>Date</strong><span>${formatDate(record.date)}</span></div>
        <div class="info-row"><strong>Time In</strong><span>${formatTime(record.time_in)}</span></div>
        <div class="info-row"><strong>Time Out</strong><span>${record.time_out ? formatTime(record.time_out) : 'Session Open'}</span></div>
        <div class="info-row"><strong>Rendered Hours</strong><span>${Number(record.rendered_hours || 0).toFixed(2)} hrs</span></div>
        <div class="info-row"><strong>Status</strong><span>${renderStatusBadge(record.status)}</span></div>
        <div class="info-row"><strong>Task</strong><span>${task ? `${escapeHtml(task.title)} ${renderStatusBadge(task.status)}` : '<em>No submitted task</em>'}</span></div>
        ${task ? `<div class="info-row"><strong>Attachments</strong><span>${renderAttachments(task.attachments)}</span></div>` : ''}
      </div>
    `;
  }

  function renderClassroomDtrCalendar() {
    const year = selectedClassroomDtrMonth.getFullYear();
    const month = selectedClassroomDtrMonth.getMonth();
    const firstDay = new Date(year, month, 1);
    const lastDay = new Date(year, month + 1, 0);
    const days = [];

    for (let index = 0; index < firstDay.getDay(); index += 1) days.push({ empty: true });
    for (let day = 1; day <= lastDay.getDate(); day += 1) {
      const isoDate = getLocalDateKey(new Date(year, month, day));
      days.push({
        day,
        isoDate,
        record: selectedClassroomAttendance.find(item => getDateValue(item.date) === isoDate),
      });
    }
    while (days.length % 7 !== 0) days.push({ empty: true });

    const dayNames = ['SUN', 'MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT'];
    return `
      <div class="detail-panel-actions">
        <button type="button" class="btn-secondary" onclick="changeClassroomDtrMonth(-1)">Prev</button>
        <strong>${String(month + 1).padStart(2, '0')}/${year}</strong>
        <button type="button" class="btn-secondary" onclick="changeClassroomDtrMonth(1)">Next</button>
      </div>
      <div class="dtr-calendar-layout">
        <div>
          <div class="dtr-calendar-grid" style="margin-bottom:8px;">
            ${dayNames.map(name => `<div class="dtr-calendar-day-name">${name}</div>`).join('')}
          </div>
          <div class="dtr-calendar-grid">
            ${days.map(day => {
              if (day.empty) return '<div></div>';
              const record = day.record;
              const task = record ? getTaskForAttendance(record.id) : null;
              const border = record ? (task ? '2px solid #10B981' : (record.time_out ? '2px solid #F59E0B' : '1px solid #CBD5E1')) : '1px solid #E5E7EB';
              return `<button type="button" class="dtr-calendar-day" ${record ? '' : 'disabled'} onclick="selectClassroomDtrDate('${day.isoDate}')" style="border:${border};">${day.day}</button>`;
            }).join('')}
          </div>
        </div>
        <div id="classroom-dtr-date-details" style="border:1px solid #E5E7EB;border-radius:8px;padding:16px;background:#FFFFFF;">
          ${renderClassroomDtrDetails(null)}
        </div>
      </div>
    `;
  }

  function renderClassroomDtrTable() {
    return `
      <div style="overflow-x:auto;">
        <table class="solid-table">
          <thead>
            <tr>
              <th>Date</th>
              <th>Time In</th>
              <th>Time Out</th>
              <th>Rendered Hours</th>
              <th>Status</th>
              <th>Submitted Task</th>
            </tr>
          </thead>
          <tbody>
            ${selectedClassroomAttendance.length > 0 ? selectedClassroomAttendance.map(record => {
              const task = getTaskForAttendance(record.id);
              return `
                <tr>
                  <td>${formatDate(record.date)}</td>
                  <td>${formatTime(record.time_in)}</td>
                  <td>${record.time_out ? formatTime(record.time_out) : 'Session Open'}</td>
                  <td>${Number(record.rendered_hours || 0).toFixed(2)} hrs</td>
                  <td>${renderStatusBadge(record.status)}</td>
                  <td>${task ? `${escapeHtml(task.title)} ${renderStatusBadge(task.status)}` : '<em>No submitted task</em>'}</td>
                </tr>
              `;
            }).join('') : '<tr><td colspan="6" style="text-align:center;">No DTR records found for this classroom.</td></tr>'}
          </tbody>
        </table>
      </div>
    `;
  }

  function renderClassroomDtrPanel(view = 'date') {
    return `
      <div class="detail-panel-actions">
        <div class="calendar-legend">
          <span class="calendar-legend-item"><span class="calendar-legend-swatch" style="border:2px solid #F59E0B;"></span>Time in/out</span>
          <span class="calendar-legend-item"><span class="calendar-legend-swatch" style="border:2px solid #10B981;"></span>With submitted task</span>
        </div>
        <div class="dtr-view-toggle">
          <button type="button" class="${view === 'date' ? 'btn-primary' : 'btn-secondary'}" onclick="switchClassroomDtrView('date')">By Date</button>
          <button type="button" class="${view === 'table' ? 'btn-primary' : 'btn-secondary'}" onclick="switchClassroomDtrView('table')">By Table</button>
        </div>
      </div>
      ${view === 'date' ? renderClassroomDtrCalendar() : renderClassroomDtrTable()}
    `;
  }

  function updateJoinFormState(classrooms) {
    const hasActiveEnrollment = classrooms.some(c => !c.pivot || c.pivot.status === 'active');
    const input = document.getElementById('join-code');
    const button = document.getElementById('join-classroom-button');
    const note = document.getElementById('join-classroom-note');

    input.disabled = hasActiveEnrollment;
    button.disabled = hasActiveEnrollment;
    button.style.opacity = hasActiveEnrollment ? '0.6' : '1';
    button.style.cursor = hasActiveEnrollment ? 'not-allowed' : 'pointer';
    note.textContent = hasActiveEnrollment
      ? 'You are already enrolled in a classroom. Leave your current class before joining another.'
      : 'Enter the 5-digit Classroom Invitation Code generated by your instructor.';
  }

  async function loadClassrooms() {
    const tbody = document.getElementById('classroom-list-tbody');
    try {
      const classrooms = await apiRequest('/student/classroom');
      enrolledClassrooms = classrooms;
      updateJoinFormState(classrooms);

      tbody.innerHTML = classrooms.length > 0 ? classrooms.map(c => `
        <tr>
          <td><strong>${escapeHtml(c.classroom_name)}</strong></td>
          <td><code>${escapeHtml(c.classroom_code)}</code></td>
          <td>${escapeHtml(c.teacher && c.teacher.user ? c.teacher.user.name : 'N/A')}</td>
          <td>${escapeHtml(c.required_hours)} hrs</td>
          <td><span class="badge badge-approved">${escapeHtml(c.pivot ? c.pivot.status : 'active')}</span></td>
          <td>
            <button type="button" class="icon-action-button" aria-label="View classroom information" title="Classroom information" onclick="showClassroomInfo(${c.id})">
              <svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="10"/><path d="M12 16v-4M12 8h.01"/></svg>
            </button>
          </td>
          <td>
            <div style="display:flex; gap:8px; flex-wrap:wrap;">
              <button type="button" onclick="handleLeaveClassroom(${c.id})" class="btn-danger" style="padding:6px 12px; font-size:12px;">Leave Class</button>
            </div>
          </td>
        </tr>
      `).join('') : '<tr><td colspan="7" style="text-align:center;">Not enrolled in any classrooms yet.</td></tr>';
    } catch(err) {}
  }
  loadClassrooms();

  async function handleJoinClassroom(e) {
    e.preventDefault();
    const code = document.getElementById('join-code').value;
    try {
      const res = await apiRequest('/student/classroom/join', 'POST', { classroom_code: code });
      showToast(res.message);
      document.getElementById('join-code').value = '';
      loadClassrooms();
    } catch(err) {}
  }

  function switchClassroomInfoTab(tab) {
    const classroom = getSelectedClassroom();
    if (!classroom) return;

    ['info', 'tasks', 'dtr'].forEach(item => {
      const button = document.getElementById(`classroom-tab-${item}`);
      if (button) button.classList.toggle('active', item === tab);
    });

    const content = document.getElementById('classroom-info-content');
    if (tab === 'tasks') {
      content.innerHTML = renderClassroomTasksPanel();
    } else if (tab === 'dtr') {
      content.innerHTML = renderClassroomDtrPanel('date');
    } else {
      content.innerHTML = renderClassroomInfoPanel(classroom);
    }
  }

  function switchClassroomDtrView(view) {
    document.getElementById('classroom-info-content').innerHTML = renderClassroomDtrPanel(view);
  }

  function changeClassroomDtrMonth(offset) {
    selectedClassroomDtrMonth = new Date(selectedClassroomDtrMonth.getFullYear(), selectedClassroomDtrMonth.getMonth() + offset, 1);
    switchClassroomDtrView('date');
  }

  function selectClassroomDtrDate(dateString) {
    const record = selectedClassroomAttendance.find(item => getDateValue(item.date) === dateString);
    const details = document.getElementById('classroom-dtr-date-details');
    if (details) details.innerHTML = renderClassroomDtrDetails(record);
  }

  async function showClassroomInfo(classroomId) {
    const classroom = enrolledClassrooms.find(c => Number(c.id) === Number(classroomId));
    if (!classroom) return;

    selectedClassroomId = classroomId;
    selectedClassroomTasks = [];
    selectedClassroomAttendance = [];
    selectedClassroomDtrMonth = new Date();
    const modal = document.getElementById('classroom-info-modal');
    const title = document.getElementById('classroom-info-title');
    const content = document.getElementById('classroom-info-content');
    title.textContent = classroom.classroom_name;
    content.innerHTML = '<div style="text-align:center;padding:24px;">Loading classroom details...</div>';
    modal.hidden = false;
    modal.setAttribute('aria-hidden', 'false');

    try {
      const [tasksRes, dtrRes] = await Promise.all([
        apiRequest(`/student/tasks?classroom_id=${classroomId}&per_page=100`),
        apiRequest(`/student/dtr?classroom_id=${classroomId}&per_page=100`),
      ]);
      selectedClassroomTasks = tasksRes.data || [];
      selectedClassroomAttendance = dtrRes.attendance_records ? (dtrRes.attendance_records.data || []) : [];
      switchClassroomInfoTab('info');
    } catch (err) {}
  }

  function closeClassroomInfo() {
    const modal = document.getElementById('classroom-info-modal');
    selectedClassroomId = null;
    selectedClassroomTasks = [];
    selectedClassroomAttendance = [];
    modal.hidden = true;
    modal.setAttribute('aria-hidden', 'true');
  }

  async function handleLeaveClassroom(classroomId) {
    const classroom = enrolledClassrooms.find(c => c.id === classroomId);
    const confirmed = await showAppConfirm(`Leave ${classroom ? classroom.classroom_name : 'this classroom'}?`);
    if (!confirmed) return;

    try {
      const res = await apiRequest(`/student/classroom/${classroomId}/leave`, 'DELETE');
      showToast(res.message);
      loadClassrooms();
    } catch (err) {}
  }
</script>
@endsection
