@extends('layouts.student')

@section('title', 'Classroom Integration — TrackTern')
@section('page_heading', 'Classroom Integration')
@section('nav_classroom', 'active')

@section('content')
<div class="table-container" style="padding: 24px; margin-bottom: 30px;">
  <h3>Join Teacher's Classroom</h3>
  <p style="font-size: 14px; color: #4B5563; margin-bottom: 16px;">Enter the 5-digit Classroom Invitation Code generated by your instructor.</p>
  <form onsubmit="handleJoinClassroom(event)" style="display: flex; gap: 16px; max-width: 450px;">
    <input type="text" id="join-code" placeholder="Enter 5-digit Code (e.g. CR902)" maxlength="5" style="text-transform: uppercase; font-weight:700;" required>
    <button type="submit" class="btn-primary" style="white-space: nowrap;">Join Class</button>
  </form>
</div>

<div class="table-container">
  <div class="table-header">
    <h3>Enrolled Classrooms</h3>
  </div>
  <table class="solid-table">
    <thead>
      <tr>
        <th>Classroom Name</th>
        <th>Code</th>
        <th>Teacher</th>
        <th>Required Hours</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody id="classroom-list-tbody">
      <tr><td colspan="5" style="text-align:center;">Loading classroom enrollments...</td></tr>
    </tbody>
  </table>
</div>
@endsection

@section('scripts')
<script>
  async function loadClassrooms() {
    const tbody = document.getElementById('classroom-list-tbody');
    try {
      const classrooms = await apiRequest('/student/classroom');
      tbody.innerHTML = classrooms.length > 0 ? classrooms.map(c => `
        <tr>
          <td><strong>${c.classroom_name}</strong></td>
          <td><code>${c.classroom_code}</code></td>
          <td>${c.teacher && c.teacher.user ? c.teacher.user.name : 'N/A'}</td>
          <td>${c.required_hours} hrs</td>
          <td><span class="badge badge-approved">${c.pivot ? c.pivot.status : 'active'}</span></td>
        </tr>
      `).join('') : '<tr><td colspan="5" style="text-align:center;">Not enrolled in any classrooms yet.</td></tr>';
    } catch(err) {}
  }
  loadClassrooms();

  async function handleJoinClassroom(e) {
    e.preventDefault();
    const code = document.getElementById('join-code').value;
    try {
      const res = await apiRequest('/student/classroom/join', 'POST', { classroom_code: code });
      showToast(res.message);
      document.getElementById('join-code').value = '';
      loadClassrooms();
    } catch(err) {}
  }
</script>
@endsection
